export type AdditionalAuditQuestion = {
  key: string
  section: string
  text: string
  critical?: boolean
  weight: number
}

export const warehouseQuestions: AdditionalAuditQuestion[] = [
  {
    key: "warehouse_floors",
    section: "Cleanliness and Facility Condition",
    text: "Are floors clean and free from excessive oil, grease, water, trash and debris?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_walkways",
    section: "Cleanliness and Facility Condition",
    text: "Are walkways, entrances, work areas and emergency exits clear and accessible?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_surfaces",
    section: "Cleanliness and Facility Condition",
    text: "Are walls, doors, shelving and work surfaces reasonably clean and maintained?",
    weight: 2,
  },
  {
    key: "warehouse_grease_control",
    section: "Cleanliness and Facility Condition",
    text: "Is the warehouse free from excessive grease, grime, oil residue and unpleasant odors?",
    weight: 2,
  },
  {
    key: "warehouse_waste",
    section: "Cleanliness and Facility Condition",
    text: "Are trash, waste oil, used filters and other waste materials contained and removed properly?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_pest_control",
    section: "Cleanliness and Facility Condition",
    text: "Is the warehouse free from visible pest, sanitation or contamination concerns?",
    weight: 2,
  },
  {
    key: "warehouse_equipment_storage",
    section: "Organization and Responsibilities",
    text: "Are MFUs, MBUs, vacuums, hoses and other service equipment stored safely and orderly?",
    weight: 2,
  },
  {
    key: "warehouse_clean_dirty_separation",
    section: "Organization and Responsibilities",
    text: "Are clean equipment and supplies appropriately separated from dirty equipment and waste materials?",
    weight: 2,
  },
  {
    key: "warehouse_inventory",
    section: "Organization and Responsibilities",
    text: "Are filters, chemicals, tools, parts, PPE and operating supplies organized and adequately stocked?",
    weight: 2,
  },
  {
    key: "warehouse_damaged_equipment",
    section: "Organization and Responsibilities",
    text: "Is damaged or out-of-service equipment clearly identified and separated from service-ready equipment?",
    weight: 2,
  },
  {
    key: "warehouse_routine_duties",
    section: "Organization and Responsibilities",
    text: "Are routine cleaning, inspection, maintenance and inventory responsibilities being completed?",
    weight: 3,
  },
  {
    key: "warehouse_maintenance_area",
    section: "Organization and Responsibilities",
    text: "Is the maintenance and repair area organized, functional and free from avoidable hazards?",
    weight: 2,
  },
  {
    key: "warehouse_chemical_storage",
    section: "Safety and Compliance",
    text: "Are chemicals labeled, closed and stored safely with incompatible materials separated?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_spill_kit",
    section: "Safety and Compliance",
    text: "Is a complete and accessible spill kit available?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_fire_extinguishers",
    section: "Safety and Compliance",
    text: "Are fire extinguishers present, accessible, inspected and current?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_ppe",
    section: "Safety and Compliance",
    text: "Is required PPE available, organized and in usable condition?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_electrical",
    section: "Safety and Compliance",
    text: "Are outlets, extension cords, chargers, batteries and electrical equipment being used safely?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_oil_containment",
    section: "Safety and Compliance",
    text: "Are fresh oil and used oil stored with appropriate containment and without active leaks?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_6k_area",
    section: "Oil Storage System",
    text: "Is the oil storage system area clean, orderly and free from unnecessary materials?",
    weight: 2,
  },
  {
    key: "warehouse_6k_components",
    section: "Oil Storage System",
    text: "Are the oil storage tanks, pumps, hoses, valves and fittings in good condition and functioning properly?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_6k_leaks",
    section: "Oil Storage System",
    text: "Is the oil storage system free from active leaks, drips and excessive oil residue?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_6k_containment",
    section: "Oil Storage System",
    text: "Is secondary containment clean, intact and capable of containing a spill?",
    critical: true,
    weight: 3,
  },
  {
    key: "warehouse_6k_labels",
    section: "Oil Storage System",
    text: "Are tanks, lines, valves and fill points clearly labeled, including fresh-oil and used-oil systems?",
    critical: true,
    weight: 2,
  },
  {
    key: "warehouse_6k_levels",
    section: "Oil Storage System",
    text: "Are tank levels being monitored and recorded accurately?",
    weight: 2,
  },
  {
    key: "warehouse_6k_transfers",
    section: "Oil Storage System",
    text: "Are oil transfers, pickups and deliveries being completed and documented properly?",
    weight: 2,
  },
  {
    key: "warehouse_6k_access",
    section: "Oil Storage System",
    text: "Is access to the oil storage system appropriately controlled and free from obstruction?",
    critical: true,
    weight: 2,
  },
]

export const vehicleQuestions: AdditionalAuditQuestion[] = [
  {
    key: "vehicle_starts_operates",
    section: "Function and Road Readiness",
    text: "Does the vehicle start, idle and operate normally?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_warning_lights",
    section: "Function and Road Readiness",
    text: "Is the vehicle free from unresolved dashboard warning lights or operating alerts?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_lights_signals",
    section: "Function and Road Readiness",
    text: "Are the headlights, brake lights, turn signals and hazard lights functioning?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_tires",
    section: "Function and Road Readiness",
    text: "Are the tires properly inflated and free from unsafe wear or visible damage?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_brakes",
    section: "Function and Road Readiness",
    text: "Do the service brakes and parking brake function properly?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_mirrors_doors",
    section: "Function and Road Readiness",
    text: "Are the mirrors, windshield, wipers, doors, locks and windows in safe operating condition?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_maintenance",
    section: "Function and Road Readiness",
    text: "Is required vehicle maintenance current, with known mechanical issues being addressed?",
    weight: 2,
  },
  {
    key: "vehicle_exterior_clean",
    section: "Condition and Presentation",
    text: "Is the exterior clean and professionally presentable?",
    weight: 2,
  },
  {
    key: "vehicle_branding",
    section: "Condition and Presentation",
    text: "Is Dorado and Filta branding clean, visible and in good condition?",
    weight: 2,
  },
  {
    key: "vehicle_body_condition",
    section: "Condition and Presentation",
    text: "Is the vehicle free from significant unreported body, glass or lighting damage?",
    weight: 2,
  },
  {
    key: "vehicle_cab_clean",
    section: "Condition and Presentation",
    text: "Is the cab clean, orderly and free from excessive clutter, trash and personal items?",
    weight: 2,
  },
  {
    key: "vehicle_customer_presentation",
    section: "Condition and Presentation",
    text: "Would the vehicle present professionally at a customer location?",
    weight: 2,
  },
  {
    key: "vehicle_service_area",
    section: "Service Area and Organization",
    text: "Is the service area clean, organized and free from excessive oil, grease and grime?",
    weight: 3,
  },
  {
    key: "vehicle_equipment_secured",
    section: "Service Area and Organization",
    text: "Are MFUs, MBUs, vacuums and other service equipment properly secured?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_hoses_tools_secured",
    section: "Service Area and Organization",
    text: "Are hoses, tools, containers and loose materials organized and secured against movement?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_clean_dirty_separation",
    section: "Service Area and Organization",
    text: "Are clean supplies appropriately separated from dirty tools, equipment and waste materials?",
    weight: 2,
  },
  {
    key: "vehicle_oil_containers",
    section: "Service Area and Organization",
    text: "Are fresh-oil and used-oil containers closed, secured, labeled and free from leaks?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_route_supplies",
    section: "Service Area and Organization",
    text: "Are required filters, chemicals, PPE, tools and route supplies stocked?",
    weight: 2,
  },
  {
    key: "vehicle_spill_kit",
    section: "Safety Equipment",
    text: "Is a complete and accessible spill kit present?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_fire_extinguisher",
    section: "Safety Equipment",
    text: "Is a current and accessible fire extinguisher present?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_first_aid",
    section: "Safety Equipment",
    text: "Is a stocked and accessible first-aid kit present?",
    critical: true,
    weight: 2,
  },
  {
    key: "vehicle_ppe",
    section: "Safety Equipment",
    text: "Is all required PPE present and in usable condition?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_documents",
    section: "Safety Equipment",
    text: "Are registration, insurance and required inspection documents current and available?",
    critical: true,
    weight: 3,
  },
  {
    key: "vehicle_route_ready",
    section: "Safety Equipment",
    text: "Is the vehicle safe, clean, stocked and fully prepared to complete its assigned route?",
    critical: true,
    weight: 3,
  },
]
